### ISSUE TITLE
Error LoggerProxy not initialized

### ISSUE THREAD

**Issue by lexoyo** [ETdoFresh/n8n-nodes-mastodon#4]
Hello,
Thank you @ETdoFresh for the great node !!!
When I setup an empty workflow with just a mastodon search, it gives me an error: `LoggerProxy not initialized`, which I'm guessing [comes form here](https://github.com/ETdoFresh/n8n-nodes-mastodon/blob/b3dedc1163fb831232eb4915dcb8bd7bc0302b4e/nodes/Mastodon/Mastodon_Methods.ts#L4)?

![Screenshot from 2023-01-02 15-16-20](https://user-images.githubusercontent.com/715377/210243188-d2703962-c099-4f22-9651-bddfdc1c019c.png)

```
NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.mastodonApiRequest (/root/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:187:9)
    at Object.search (/root/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:118:36)
    at Object.execute (/root/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:25:42)
    at Object.execute (/root/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon.node.ts:41:48)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:658:51)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:585:68
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Let me know if I can help fix this bug, and if it is even a bug?
Thanks again!

**Comment by ETdoFresh** [comment]
Hey, I'll take a look next week. Will be back from vacation then.

**Comment by ETdoFresh** [comment]
Just looking into the issues now. I'll write back in a bit to tell you what I find out. Stand by! :)

**Comment by ETdoFresh** [comment]
Hmm. IDK! I just ran on mine... and this is what I see... looks almost identical to what you have. I don't really know the Mastodon URLs out there... but maybe perhaps remove the backslash (/) from the end of the url? Let me know if that does anything?
![image](https://user-images.githubusercontent.com/1261843/213346526-0e815dd2-fa0a-47eb-b492-77d3a7c2cf40.png)

**Comment by ETdoFresh** [comment]
~Wait, you gave me some much context and I missed it... sorry... being totally blind! I'll remove the LoggerProxy and publish another version up.~

**Comment by ETdoFresh** [comment]
Well OK... now I'm back tracking a bit. I have the Logger to log out important debug information if needed. I want to keep it so users can see what data is being sent out if they set their logging level to `debug`. Not exactly sure why you don't have LoggerProxy in your "n8n-workflow" instance.

**Comment by lexoyo** [comment]
I don't know either :-/

I use the latest docker image, automatically installed with https://coolify.io/

I should check the env vars maybe

**Comment by lexoyo** [comment]
Here is the Docker image i use
[0.210.1](https://hub.docker.com/layers/n8nio/n8n/0.210.1/images/sha256-5131c8ab02e46ed30f0bdeae8739d1c1e4734959192cb46e020034a26dde1c92?context=explore)

Here are the env vars I use
https://github.com/lexoyo/n8n-docker-compose/blob/main/docker-compose.yml

I don't see anything suspicious :-/

**Comment by benborges** [comment]
Very odd,  I use Cloudron to run N8N, I have the latest N8N version but on 1 N8N instance with the same Mastodon node module I don't have any issue and on another, same infrastructure, same version, I have this error. 

`NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.mastodonApiRequest (/app/data/user/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:195:9)
    at Object.create (/app/data/user/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:88:35)
    at Object.execute (/app/data/user/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:19:42)
    at Object.execute (/app/data/user/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon.node.ts:41:48)
    at Workflow.runNode (/app/code/node_modules/n8n-workflow/src/Workflow.ts:1270:42)
    at /app/code/node_modules/n8n-core/src/WorkflowExecute.ts:938:44
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by lexoyo** [comment]
I don't see the "LoggerProxy not initialized" error in your logs, am I missing something or is it a different error?

**Comment by benborges** [comment]
My bad, I copied the stack trace and forgot to add : 

Also asked about this on N8N forum : https://community.n8n.io/t/0-159-1-loggerproxy-not-initialized/10768/4

![image](https://user-images.githubusercontent.com/10617712/218307672-dc57e44b-cfd3-44d9-a080-34b49fa8c9ec.png)

**Comment by jakevis** [comment]
https://github.com/n8n-io/n8n/issues/5721

Seems that this has been IDed as larger issue maybe

**Comment by bartv42** [comment]
I'm running into the same issue. Did anyone manage to resolve this?

**Comment by rmdes** [comment]
Having the same issue since 2 weeks LoggerProxy not initialized
on Version 0.228.2

**Comment by rmdes** [comment]
This is still ongoing, rendering this node not usable for now :/
